'use strict';

var YAHOO_WEATHER_API_ENDPOINT = 'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22london%2C%20uk%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys';

// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
self.addEventListener('push', function(event) {
  console.log('Received a push message', event);

  // Since this is no payload data with the first version
  // of Push notifications, here we'll grab some data from
  // an API and use it to populate a notification
  event.waitUntil(
    fetch(YAHOO_WEATHER_API_ENDPOINT).then(function(response) {
      if (response.status !== 200) {
        console.log('Looks like there was a problem. Status Code: ' + response.status);
        return;
      }

      // Examine the text in the response
      return response.json().then(function(data) {
        var title = 'What\'s the weather like in London?';
        var message = 'Well, we have ' +
          data.query.results.channel.item.condition.text.toLowerCase() +
          ' at the moment';
        var icon = data.query.results.channel.image.url || 
          'images/touch/chrome-touch-icon-192x192.png';

        // Add this to the data of the notification
        var urlToOpen = data.query.results.channel.link;

        return self.registration.showNotification(title, {
          body: message,
          icon: icon,
          tag: 'simple-push-demo-notification',
          data: {
            url: urlToOpen
          }
        });
      });
    }).catch(function(e) {
      console.log('Unable to retrieve data');
    })
  );
});

self.addEventListener('pushsubscriptionlost', function(e) {
  console.log('Push subscription lost' + e);
});

self.addEventListener('notificationclick', function(e) {
  console.log('On notification click: ', e);

  // At the time of implementation e.notification.data wasn't implemented
  var urlToOpen = e.notification.data ? e.notification.data.url :
    'https://gauntface.com/blog/2014/12/15/push-notifications-service-worker';
  
  // At the moment you cannot open third party URL's, a simple trick
  // is to redirect to the desired URL from a URL on your domain
  var redirectUrl = self.location.origin + '/redirect.html?redirect=' +
    urlToOpen;
  clients.openWindow(redirectUrl);
});
